routes/web.php
<?php

use App\Http\Controllers\TodoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [TodoController::class, 'index'])->name('todos.index');
Route::resource('todos', TodoController::class);
Route::get('todos/{todo}/complete', [TodoController::class, 'complete'])->name('todos.complete');

app/Models/Todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    use HasFactory;

    protected $fillable=['title','description','completed'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Todo;
use Illuminate\Http\Request;


class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todos = Todo::latest()->paginate(5);
        return view('todos.index', compact('todos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required'
        ]);

        Todo::create([
            'title'=>$request->title,
            'description'=>$request->description
        ]);

        return redirect(route('todos.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function show(Todo $todo)
    {
        return view('todos.show', compact('todo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function edit(Todo $todo)
    {
        return view('todos.edit',compact('todo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Todo $todo)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required'
        ]);

        $todo->update([
            'title'=>$request->title,
            'description'=>$request->description
        ]);


        alert()->success('با تشکر','تسک مورد نظر با موفقیت ویرایش شد');

        return redirect(route('todos.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Todo $todo)
    {
        $todo->delete();
        alert()->warning('دقت','تسک مورد نظر با موفقیت حذف شد');
        return redirect(route('todos.index'));
    }

    public function complete(Todo $todo)
    {
        $todo->update([
            'completed'=>true
        ]);

        alert()->success('با تشکر','تسک مورد نظر به انجام شده تغییر وضعیت یافت');

        return redirect(route('todos.index'));
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Laravel9 Todo List </title>
    <link rel="stylesheet" href="{{mix('css/app.css')}}">
</head>
<body>
    @include('sweetalert::alert')
    @yield('content')

    <script src="{{mix('js/app.js')}}"></script>
</body>
</html>

resources/views/todos/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        تسک جدید
                    </div>
                    <div class="card-body">
                        <form action="{{ route('todos.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label class="form-label" for="title">نام</label>
                                <input class="form-control  @error('title')  is-invalid  @enderror" type="text" name="title" id="title" value="{{ old('title') }}">
                                @error('title')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label class="form-label" for="description">توضیحات</label>
                                <textarea class="form-control @error('description')  is-invalid  @enderror" name="description" id="description" rows="4">{{ old('description') }}</textarea>
                                @error('description')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <button class="btn btn-info" type="submit">ذخیره</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/todos/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        ویرایش تسک
                    </div>
                    <div class="card-body">
                        <form action="{{ route('todos.update',['todo'=>$todo->id]) }}" method="post">
                            @csrf
                            @method('put')
                            <div class="mb-3">
                                <label class="form-label" for="title">نام</label>
                                <input class="form-control  @error('title')  is-invalid  @enderror" type="text" name="title" id="title" value="{{ $todo->title }}">
                                @error('title')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label class="form-label" for="description">توضیحات</label>
                                <textarea class="form-control @error('description')  is-invalid  @enderror" name="description" id="description" rows="4">{{ $todo->description }}</textarea>
                                @error('description')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <button class="btn btn-info" type="submit">تأیید</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/todos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="d-flex justify-content-between my-3">
                    <h4>لیست تسک ها</h4>
                    <a class="btn btn-outline-success" href="{{ route('todos.create') }}">تسک جدید</a>
                </div>
                <div class="card">
                    <div class="card-header">
                        تسک ها
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            @foreach ($todos as $todo)
                                <li class="list-group-item card-title d-flex justify-content-between">{{ $todo->title }}
                                    <div>
                                        <a class="btn btn-primary"
                                            href="{{ route('todos.show', ['todo' => $todo->id]) }}">نمایش</a>
                                        @if (!$todo->completed)
                                            <a class="btn btn-secondary"
                                                href="{{ route('todos.complete', ['todo' => $todo->id]) }}">انجام شد</a>
                                        @endif
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                        <div class="d-flex justify-content-center">
                            {{ $todos->onEachSide(2)->links() }}
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/todos/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h4 class="text-center mt-5 mb-3"> {{$todo->title}}</h4>
                <div class="card">
                    <div class="card-header">
                        توضیحات
                    </div>
                    <div class="card-body">
                          <span>{{$todo->description}}</span>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex">
                            <a class="btn btn-success" href="{{ route('todos.edit', ['todo'=>$todo->id]) }}">ویرایش</a>
                            <form action="{{ route('todos.destroy', ['todo'=>$todo->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger me-2" type="submit">حذف</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection